Repository NetsBlox/NetsBlox, pull requests merged in 2018-03, with the labels that each got.

#1887 Added (optional) s3 blob support. Closes #1559
  package-lock.json
  package.json
  src/server/storage/blob-storage.js
  src/server/storage/blob/blob.js
  src/server/storage/blob/fs.js
  src/server/storage/blob/index.js
  src/server/storage/blob/s3.js
  src/server/storage/projects.js
  src/server/storage/user-actions.js
  test/unit/server/storage/blob-storage.spec.js
  test/unit/server/storage/blob/index.spec.js
  utils/migrate-blob-backend.js
Labels: amazon, enhancement

#1889 updated the the backend api for british museum Fixes #1888
  src/server/rpc/procedures/british-museum/british-museum.js
Labels: amazon, bug

#1890 Added support for server execution of reportRPCError. Closes #1876
  src/server/rpc/blocks2js.js
Labels: bug, minor, rpcs

#1896 Added service descriptions (incl ToS). Closes #1895
  src/server/rpc/procedures/air-quality/air-quality.js
  src/server/rpc/procedures/british-museum/british-museum.js
  src/server/rpc/procedures/connect-n/connect-n.js
  src/server/rpc/procedures/earthquakes/earthquakes.js
  src/server/rpc/procedures/eclipse-2017/eclipse-2017.js
  src/server/rpc/procedures/execute/execute.js
  src/server/rpc/procedures/geolocation/geolocation.js
  src/server/rpc/procedures/google-maps/google-maps.js
  src/server/rpc/procedures/google-trends/google-trends.js
  src/server/rpc/procedures/iex-trading/iex-trading.js
  src/server/rpc/procedures/movie-db/movie-db.js
  src/server/rpc/procedures/nasa/nasa.js
  src/server/rpc/procedures/pixabay/pixabay.js
  src/server/rpc/procedures/star-map/star-map.js
  src/server/rpc/procedures/thing-speak/thing-speak.js
  src/server/rpc/procedures/traffic/traffic.js
  src/server/rpc/procedures/trivia/trivia.js
  src/server/rpc/procedures/twitter/twitter.js
  src/server/rpc/procedures/water-watch/water-watch.js
  src/server/rpc/procedures/weather/weather.js
Labels: enhancement, minor, rpcs

#1898 Fixed disconnect/reconnect bugs. Closes #1897
  src/server/rooms/netsblox-socket.js
  src/server/rooms/room-manager.js
  src/server/socket-manager.js
Labels: bug, major

#1902 Updated tests for annotation extraction. Fixes #1901
  test/unit/server/rpc/jsdoc-extractor.spec.js
Labels: bug, minor, testing

#1905 Fixed the user email appending to report. Fixes #1904
  src/server/bug-reporter.js
Labels: bug, minor

#1907 Ensure the last message was 'report-version'. Fixes #1906
  test/unit/server/rooms/netsblox-socket.js
Labels: bug, minor, testing

#1900 swapped lwip for jimp Fixes #1651
  package-lock.json
  package.json
  src/server/routes/projects.js
  test/unit/server/routes/project.js
Labels: enhancement

#1903 Added auto tests and utility for testing login/logout. Closes #1708
  test/fixtures/users.js
  test/unit/server/routes/basic-routes.js
  test/utils/login-test.html
  test/utils/sha512.js
Labels: enhancement, minor, testing

#1911 Only update role's action id if not user action. Fixes #1910
  src/server/rooms/netsblox-socket.js
Labels: bug

#1922 Added more utilities for migrating blobs. Closes #1921
  utils/list-blob-objects.js
  utils/migrate-blob-backend.js
  utils/upload-fs-to-s3.sh
Labels: amazon, enhancement, minor

#1926 Added error rewording to the IEXTrading service. Closes #1925
  src/server/rpc/procedures/iex-trading/iex-trading.js
Labels: enhancement, minor, rpcs

#1928 Diff the existing and total files for new files to upload. Closes #1927
  utils/upload-fs-to-s3.sh
Labels: enhancement, minor, utility

#1929 Added logs about bug-reporting on start
  src/server/bug-reporter.js
Labels: enhancement, minor

#1931 Updated blob list-objects to use v2. Fixes #1930
  src/server/storage/blob/s3.js
  utils/upload-fs-to-s3.sh
Labels: bug, minor

#1933 Added 'set-password' command. Fixes #1932
  bin/netsblox
  bin/netsblox-set-password.js
  src/server/storage/users.js
  test/unit/server/storage/users.spec.js
Labels: command line interface, enhancement, minor

#1935 Removed test/ from docker file
  .dockerignore
Labels: enhancement, minor

#1940 Disable doWarp when executing on the server. Fixes #1939
  src/server/rpc/blocks2js.js
Labels: bug, rpcs

#1936 Updated ws library. Closes #1934
  package-lock.json
  package.json
  src/server/rooms/netsblox-socket.js
Labels: enhancement

#1942 aadded missing socket info to RPC instance (block execution on server) fixes #1941
  src/server/rpc/blocks2js.js
Labels: amazon, bug

#1949 Added headers from upgrade req to bug report. Fixes #1948
  src/server/bug-reporter.js
Labels: enhancement, minor

#1954 Declare the socket dead if ws not open. Fixes #1951
  src/server/rooms/netsblox-socket.js
Labels: bug, major
