Repository NetsBlox/NetsBlox, pull requests merged in 2018-02, with the labels that each got.

#1878 configurable server protocol Fixes #1877
  README.md
  src/server/server.js
Labels: bug

#1883 Removed the sorting of numbers. Fixes #1882
  src/server/rpc/procedures/chart/chart.js
  test/unit/client/rpc/chart-tests.xml
Labels: minor, rpcs

#1859 improved caching for geolocation service
  src/server/rpc/procedures/geolocation/geolocation.js
  test/unit/server/rpc/procedures/geolocation.spec.js
Labels: enhancement, rpcs

#1886 Added tests for IEXTrading service. Closes #1885
  test/unit/server/rpc/procedures/iex-trading.spec.js
Labels: enhancement, minor, testing
