Repository NetsBlox/NetsBlox, pull requests merged in 2018-05, with the labels that each got.

#2030 use SERVER_PROTOCOL env variable Fixes #2029
  src/server/routes/projects.js
Labels: bug, minor

#2018 minor simplification in chart service
  src/server/rpc/procedures/chart/chart.js
  test/unit/client/rpc/chart-tests.xml
Labels: enhancement, minor

#2037 googlemaps cache precision fixes #2036
  src/server/rpc/procedures/google-maps/google-maps.js
  test/unit/server/rpc/procedures/google-maps.spec.js
Labels: enhancement

#2043 Added silent ws msg support. Closes #2042
  src/server/rooms/netsblox-socket.js
Labels: enhancement, minor

#2046 Removed markdown engine (just using html). Fixes #2014
  package-lock.json
  package.json
  src/server/bug-reporter.js
  src/server/mailer.js
  src/server/storage/users.js
Labels: amazon, bug

#2055 Compare rooms and projects by projectIds. Fixes #2054
  src/server/routes/projects.js
Labels: bug, minor

#2056 saveACopy should use setUser middleware. Closes #2053
  src/server/routes/projects.js
Labels: enhancement, minor, refactor

#2060 Use isSupported in geolocation,roboscape,moviedb services. Closes #1961
  src/server/rpc/procedures/geolocation/geolocation.js
  src/server/rpc/procedures/movie-db/movie-db.js
  src/server/rpc/procedures/roboscape/roboscape.js
Labels: enhancement, minor, testing

#2064 Added better err msg for min-only BoundedNumber. Closes #2063
  src/server/rpc/input-types.js
  test/unit/server/rpc/input-types.spec.js
Labels: enhancement, minor, rpcs

#2076 Remove the old 'this' arg to the logger. Fixes #2075
  src/server/rpc/procedures/utils/logger.js
Labels: bug, minor, rpcs

#2074 Updated tests for cancelation support. Closes #2073
  src/server/rpc/procedures/dev/dev.js
  test/assets/mock-rpc.js
  test/unit/server/rpc/procedures/earthquakes.spec.js
Labels: enhancement, minor, testing
