Repository NetsBlox/NetsBlox, pull requests merged in 2018-11, with the labels that each got.

#2264 Change how ApiConsumer determines cache keys
  src/server/rpc/procedures/utils/api-consumer.js
Labels: blocking, rpcs

#2260 Added custom cache key for Translation RPC and increased cache time Fix #2256
  src/server/rpc/procedures/azure-translation/azure-translation.js
Labels: rpcs

#2274 renewed cli project export fixed #2273
  bin/netsblox-export-project.js
  bin/utils.js
Labels: bug
