Repository NetsBlox/NetsBlox, pull requests merged in 2018-08, with the labels that each got.

#2189 Unwrap OptionalType wrappers before parsing type. Fixes #2188
  src/server/rpc/jsdoc-extractor.js
  test/unit/server/rpc/jsdoc-extractor.spec.js
Labels: bug, rpcs

#2185 Waterwatch's stop RPC replies with a promise Fixes #2184
  src/server/rpc/procedures/utils/api-consumer.js
  src/server/rpc/procedures/water-watch/water-watch.js
Labels: rpcs

#2191 disallow easy robot id matching #2190
  src/server/rpc/procedures/roboscape/roboscape.js
Labels: discussion

#2195 Support for destroying projects w/o loading. Closes #2194
  src/server/storage/projects.js
Labels: enhancement, minor, optimization

#2178 RPC Refactor WIP (#2155)
  src/server/rpc/procedures/air-quality/air-quality.js
  src/server/rpc/procedures/battleship/battleship.js
  src/server/rpc/procedures/british-museum/british-museum.js
  src/server/rpc/procedures/earthquakes/earthquakes.js
  src/server/rpc/procedures/water-watch/water-watch.js
  test/unit/server/rpc/procedures/airquality.spec.js
Labels: rpcs

#2203 Increased timeout for CloudVariables tests. Fixes #2183
  src/server/rpc/procedures/cloud-variables/cloud-variables.js
  test/unit/server/rpc/procedures/cloud-variables.spec.js
Labels: bug, minor, testing

#2205 Ensure NetworkTopology initialized in RPC tests. Fixes #2204
  src/server/client.js
  src/server/network-topology.js
  src/server/server.js
  test/assets/mock-rpc.js
  test/assets/utils.js
Labels: bug, minor, testing

#2211 Fixed auto conversion of lists of objs to lists of lists. Fixes #2210
  src/server/rpc/rpc-manager.js
  test/unit/server/rpc/rpc-manager.js
Labels: bug, minor, rpcs

#2214 Record map by client ID w/ ttl in GoogleMaps. Fixes #2213
  src/server/rpc/procedures/google-maps/google-maps.js
Labels: bug, rpcs

#2220 Dont rely on the ws conn for public role id. Fixes #2219
  src/server/rpc/procedures/public-roles/public-roles.js
Labels: bug, rpcs

#2222 Update room on remove collaborator. Fixes #2221
  src/server/routes/rooms.js
Labels: bug, minor

#2227 Copy over all contextual info in server-side RPC call. Fixes #2226
  src/server/rpc/blocks2js.js
Labels: bug, rpcs
