Repository NetsBlox/NetsBlox, pull requests merged in 2019-09, with the labels that each got.

#2442 Added width and height to chart options. Closes #2441
  src/server/rpc/procedures/chart/chart.js
  src/server/rpc/procedures/chart/node-gnuplot.js
  test/unit/server/rpc/procedures/chart/chart.spec.js
Labels: feature, services

#2444 Added throw RPC to dev service and docs for dev RPCs. Closes #2443
  src/server/rpc/procedures/dev/dev.js
Labels: feature, minor

#2448 Add OceanData service. Closes #2429
  src/server/rpc/procedures/ocean-data/Table.txt
  src/server/rpc/procedures/ocean-data/ocean-data.js
  test/unit/server/rpc/procedures/ocean-data.spec.js
Labels: enhancement, services

#2450 Combine init service logs. Removed excessive route logging. Closes #2249
  src/server/rpc/rpc-manager.js
  src/server/server.js
Labels: enhancement, minor

#2420 Add PaleoClimate Service
  src/server/rpc/procedures/paleo-climate/data/antarctic-co2-composite/antarctica2015co2composite.txt
  src/server/rpc/procedures/paleo-climate/data/antarctic-co2-composite/index.js
  src/server/rpc/procedures/paleo-climate/data/domec-deuterium/edc3deuttemp2007.txt
  src/server/rpc/procedures/paleo-climate/data/domec-deuterium/index.js
  src/server/rpc/procedures/paleo-climate/data/index.js
  src/server/rpc/procedures/paleo-climate/data/law-co2/antarctica2015co2law.txt
  src/server/rpc/procedures/paleo-climate/data/law-co2/index.js
  src/server/rpc/procedures/paleo-climate/data/law-d18O/index.js
  src/server/rpc/procedures/paleo-climate/data/law-d18O/law2012d18o.txt
  src/server/rpc/procedures/paleo-climate/data/vostok-deuterium/deutnat.txt
  src/server/rpc/procedures/paleo-climate/data/vostok-deuterium/index.js
  src/server/rpc/procedures/paleo-climate/data/wais-co2/antarctica2015co2wais.txt
  src/server/rpc/procedures/paleo-climate/data/wais-co2/index.js
  src/server/rpc/procedures/paleo-climate/data/wais-hydrogen-oxygen/index.js
  src/server/rpc/procedures/paleo-climate/data/wais-hydrogen-oxygen/wdc05a2013d18o.txt
  src/server/rpc/procedures/paleo-climate/paleo-climate.js
  src/server/rpc/procedures/utils/db-consumer.js
  test/unit/server/rpc/procedures/paleo-climate.spec.js
Labels: rpc

#2455 Set optional RPC arguments to undefined if not provided. Fixes #2454
  src/server/rpc/procedures/n-player/n-player.js
  src/server/rpc/procedures/paleo-climate/paleo-climate.js
  src/server/rpc/procedures/pixabay/pixabay.js
  src/server/rpc/procedures/twenty-questions/twenty-questions.js
  src/server/rpc/procedures/utils/db-consumer.js
  src/server/rpc/rpc-manager.js
  test/unit/server/rpc/rpc-manager.js
Labels: bug, rpc

#2452 Improved help msg for getIceCoreNames. Closes #2451
  src/server/rpc/procedures/paleo-climate/paleo-climate.js
Labels: enhancement, minor, rpc

#2457 Removed unused utility and added docs for defaultOpts. Closes #2456
  src/server/rpc/procedures/chart/chart.js
  src/server/rpc/procedures/utils/dataset-test.js
  test/unit/server/rpc/procedures/utils/dataset-test.spec.js
Labels: enhancement, minor, rpc

#2459 Update err handling and add docs for TwentyQuestions. Closes #2458
  src/server/examples/Twenty Questions/answerer.xml
  src/server/rpc/procedures/twenty-questions/twenty-questions.js
  test/unit/server/rpc/procedures/twentyquestions.spec.js
Labels: enhancement, rpc

#2462 Removed unnecessary ramda dependency. Closes #1659
  package-lock.json
  package.json
  src/server/routes/basic-routes.js
  src/server/rpc/procedures/earthquakes/earthquakes.js
  src/server/server-utils.js
Labels: enhancement, minor

#2464 Update swapped parsing files and incorrect core name. Fixes #2463
  src/server/rpc/procedures/paleo-climate/data/antarctic-co2-composite/index.js
  src/server/rpc/procedures/paleo-climate/data/domec-deuterium/index.js
  src/server/rpc/procedures/paleo-climate/data/law-co2/index.js
  src/server/rpc/procedures/paleo-climate/data/vostok-deuterium/index.js
  src/server/rpc/procedures/paleo-climate/data/wais-co2/index.js
  src/server/rpc/procedures/paleo-climate/data/wais-hydrogen-oxygen/index.js
Labels: bug, services

#2468 Ensure metadata exists for each ice core. Fixes #2467
  src/server/rpc/procedures/paleo-climate/paleo-climate.js
Labels: bug, minor, services

#2466 Add getDataAvailability to PaleoClimate. Closes #2465
  src/server/rpc/procedures/paleo-climate/paleo-climate.js
  test/unit/server/rpc/procedures/paleo-climate.spec.js
Labels: enhancement, feature, services

#2470 Add "Date Range" to PaleoClimate.getAvailableDate. Closes #2469
  src/server/rpc/procedures/paleo-climate/paleo-climate.js
Labels: enhancement, rpc

#2475 Update Traffic service to use isSupported. Closes #2474
  src/server/rpc/procedures/traffic/traffic.js
Labels: services, testing

#2476 Remove extra argument for CloudVariables.deleteUserVariable. Fixes #2473
  src/server/rpc/procedures/cloud-variables/cloud-variables.js
Labels: bug, rpc

#2461 Update defaults in DBConsumer._advancedSearch. Closes #2460
  src/server/rpc/procedures/met-museum/met-museum.js
  src/server/rpc/procedures/paleo-climate/paleo-climate.js
  src/server/rpc/procedures/utils/db-consumer.js
Labels: rpc

#2481 Rename Translation dir to match conventions. Fixes #2480
  src/server/rpc/procedures/translation/translation.js
  test/unit/server/rpc/procedures/translation.spec.js
Labels: bug, minor, services

#2478 Add service name validation on server start. Closes #2477
  src/server/rpc/rpc-manager.js
Labels: enhancement, services

#2485 Fix regex for data lines in Antarctic Composite CO2 data. Fixes #2484
  src/server/rpc/procedures/paleo-climate/data/antarctic-co2-composite/index.js
Labels: bug, rpc

#2491 Converted storage to singleton. Closes #2490
  src/server/routes/basic-routes.js
  src/server/routes/middleware.js
  src/server/routes/mobile-deploy-routes.js
  src/server/routes/projects.js
  src/server/routes/users.js
  src/server/server.js
  src/server/storage/storage.js
  test/assets/utils.js
Labels: enhancement

#2492 Add support for loading DataServices from database. Closes #2489
  src/server/rpc/data-service.js
  src/server/rpc/rpc-manager.js
  src/server/server.js
Labels: enhancement, services
