Repository NetsBlox/NetsBlox, pull requests merged in 2020-06, with the labels that each got.

#2794 Add shared project to test fixtures. Closes #2793
  test/fixtures/projects.js
Labels: enhancement, minor, testing

#2798 Minimize use of nonstandard (Q) promises.
  src/server/storage/users.js
  test/unit/server/storage/users.spec.js
Labels: enhancement, minor

#2802 Remove alpha tags from climate services. Closes #2801
  src/server/services/procedures/historical-temperature/historical-temperature.js
  src/server/services/procedures/hurricane-data/hurricane-data.js
  src/server/services/procedures/ice-core-data/ice-core-data.js
  src/server/services/procedures/mauna-loa-co2-data/mauna-loa-co2-data.js
  src/server/services/procedures/ocean-data/ocean-data.js
Labels: enhancement, services

#2806 Make returned data unique by date
  src/server/services/procedures/historical-temperature/historical-temperature.js
Labels: rpc

#2808 Add covid 19 example. Closes #2807
  src/server/examples/COVID-19Daily/myRole.xml
Labels: enhancement, examples

#2809 Remove public-projects collection. Closes #1652
  src/server/routes/basic-routes.js
  src/server/server.js
  src/server/storage/projects.js
  src/server/storage/public-projects.js
  src/server/storage/storage.js
  test/fixtures/index.js
  test/unit/server/storage/projects.js
Labels: enhancement

#2813 Add optional "word" to hangman reset RPC. Closes #2812
  src/server/services/procedures/simple-hangman/simple-hangman.js
  test/unit/server/services/procedures/simplehangman.spec.js
Labels: enhancement

#2811 Stream docs and sort/aggregate on-the-fly. Fixes #2810
  src/server/services/procedures/covid-19/data/index.js
Labels: bug, services
