Repository NetsBlox/NetsBlox, pull requests merged in 2021-03, with the labels that each got.

#3030 Add port endpoints for services
  src/server/services/procedures/iotscape/routes.js
  src/server/services/procedures/phone-iot/routes.js
  src/server/services/procedures/roboscape/routes.js
Labels: rpc

#3032 Add a couple retries to CoreNLP tests. Closes #3031
  test/unit/server/services/procedures/core-nlp.js
Labels: minor, testing

#3039 Check clients from network topology. Fixes #3038
  src/server/client.js
  src/server/network-topology.js
  src/server/server-utils.js
  test/unit/server/client.js
  test/unit/server/network-topology.js
Labels: bug

#3040 Update ws dependency to 7.4.3
  package-lock.json
  package.json
Labels: dependencies, enhancement

#3041 Rename get{Sockets,Clients}At{,Project} in NetworkTopology
  src/server/api/core/projects.js
  src/server/client.js
  src/server/network-topology.js
  src/server/routes/basic-routes.js
  src/server/routes/middleware.js
  src/server/routes/rooms.js
  src/server/routes/users.js
  src/server/server.js
  test/features/collaboration.spec.js
  test/unit/server/client.js
Labels: enhancement, refactor

#3043 Improve performance of client lookup. Closes #3037
  src/server/client.js
  src/server/network-topology/client-registry.js
  src/server/network-topology/index.js
  src/server/routes/middleware.js
  test/unit/server/client.js
  test/unit/server/network-topology/client-registry.js
  test/unit/server/network-topology/index.js
Labels: enhancement, performance

#3045 Improve grade dialog open detection. Fixes #3044
  src/server/services/procedures/autograders/template.ejs
Labels: bug

#3046 Refactor client dicts to custom data structure
  src/server/network-topology/client-registry.js
  src/server/network-topology/nested-dict.js
  test/unit/server/client.js
  test/unit/server/network-topology/nested-dict.js
Labels: refactor

#3048 Don't send ping if ws reconnecting. Fixes #3047
  src/server/client.js
Labels: bug, minor

#3050 Fix IoTScape timeouts
  src/server/services/procedures/iotscape/iotscape-services.js
Labels: rpc

#3053 Update Autograder routes. Closes #3052
  src/server/services/procedures/autograders/routes.js
Labels: services

#3058 Add data parsing for Quelccaya, Huascaran ice cores. Closes #3055
  src/server/services/procedures/ice-core-data/data/quelccaya2013/README.md
  src/server/services/procedures/ice-core-data/data/quelccaya2013/huascaran.csv
  src/server/services/procedures/ice-core-data/data/quelccaya2013/index.js
  src/server/services/procedures/ice-core-data/data/quelccaya2013/qnd.csv
  src/server/services/procedures/ice-core-data/data/quelccaya2013/qsd.csv
  src/server/services/procedures/ice-core-data/data/quelccaya2013/quelccaya-trimmed.xlsx
  src/server/services/procedures/ice-core-data/data/quelccaya2013/quelccaya2013.xlsx
  src/server/services/procedures/ice-core-data/ice-core-data.js
Labels: enhancement, services

#3061 Update ice core metadata. Fixes #3060
  src/server/services/procedures/ice-core-data/data/quelccaya2013/index.js
  src/server/services/procedures/ice-core-data/ice-core-data.js
  test/unit/server/services/procedures/ice-core-data.spec.js
Labels: bug, services

#3063 Fix data label for new ice cores. Fixes #3062
  src/server/services/procedures/ice-core-data/data/quelccaya2013/index.js
Labels: bug, services
