Repository NetsBlox/NetsBlox, pull requests merged in 2021-06, with the labels that each got.

#3138 Skip unsupported services during doc generation. Fixes #3137
  bin/build-docs.js
Labels: bug

#3146 Repeat number messages for RoboScape key
  src/server/services/procedures/roboscape/robot.js
Labels: rpc

#3155 Show group ID in group list. Closes #3154
  bin/netsblox-groups-list.js
Labels: command line interface, enhancement

#3162 Kill long-running tests in autograder. Fixes #3161
  src/server/services/procedures/autograders/template.ejs
Labels: bug, services

#3164 Limit number of search results. Release ProjectGutenberg. Close #3163
  src/server/services/procedures/project-gutenberg/project-gutenberg.js
Labels: services
