Repository NetsBlox/NetsBlox, pull requests merged in 2021-02, with the labels that each got.

#3005 Add projects API endpoint. Fixes #3004
  src/server/api/rest/projects.js
Labels: bug

#3006 Add github action for running tests
  .github/workflows/node.js.yml
  .travis.yml
Labels: enhancement, testing

#3013 Add colons to acceptable autograder name chars. Closes #3012
  src/server/services/procedures/autograders/autograders.js
Labels: enhancement, minor, services

#3016 Encode ParallelDots args as URI components. Fixes #3015
  src/server/services/procedures/paralleldots/paralleldots.js
Labels: bug, services

#3001 IoTScape
  src/server/services/community/device-service.js
  src/server/services/community/index.js
  src/server/services/procedures/iotscape/iotscape-services.js
  src/server/services/procedures/iotscape/iotscape.js
  test/unit/server/services/procedures/iotscape.spec.js
Labels: rpc

#3024 Ensure reconnected sockets are still checked. Fixes #3023
  src/server/client.js
  test/unit/server/client.js
Labels: bug

#3026 Blockify expected val if list. Fixes #3025
  src/server/services/procedures/autograders/template.ejs
Labels: bug

#3028 Add some remote development debugging capabilities. Fixes #3027
  src/server/services/procedures/dev/dev.js
  src/server/services/procedures/utils/dev-logger.js
  test/unit/server/services/procedures/utils/dev-logger.js
Labels: enhancement
